# Generated by Django 3.0.7 on 2020-07-06 13:05

import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255, null=True)),
                ('url_key', models.CharField(max_length=255, null=True)),
                ('lien', models.URLField(max_length=255, null=True)),
                ('image', models.FileField(null=True, upload_to='imagecategorie')),
                ('image_nom', models.CharField(max_length=255, null=True)),
                ('image_url', models.CharField(max_length=255, null=True)),
                ('statut', models.BooleanField(default=False, null=True)),
                ('date_add', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_upd', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name': 'Categorie',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255, null=True)),
                ('nom_auteur', models.CharField(max_length=255, null=True)),
                ('couleur_article', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), null=True, size=None)),
                ('lien', models.URLField(max_length=255, null=True)),
                ('statut', models.BooleanField(default=False, null=True)),
                ('date_add', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_upd', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name': 'Collection',
                'verbose_name_plural': 'Collections',
            },
        ),
        migrations.CreateModel(
            name='SousCategorie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255, null=True)),
                ('lien', models.URLField(max_length=255, null=True)),
                ('statut', models.BooleanField(default=False, null=True)),
                ('date_add', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_upd', models.DateTimeField(auto_now=True, null=True)),
                ('categorie', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categorie', to='myapp.Categorie')),
            ],
            options={
                'verbose_name': 'SousCategorie',
                'verbose_name_plural': 'SousCategories',
            },
        ),
        migrations.CreateModel(
            name='SousCategorieItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255, null=True)),
                ('lien', models.URLField(max_length=255, null=True)),
                ('statut', models.BooleanField(default=False, null=True)),
                ('date_add', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_upd', models.DateTimeField(auto_now=True, null=True)),
                ('categorie', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='souscategorie', to='myapp.SousCategorie')),
            ],
            options={
                'verbose_name': 'SousCategorieItem',
                'verbose_name_plural': 'SousCategorieItems',
            },
        ),
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255, null=True)),
                ('lien', models.URLField(max_length=255, null=True)),
                ('prix', models.CharField(max_length=255, null=True)),
                ('prix_reduit', models.CharField(max_length=255, null=True)),
                ('nom_marque', models.CharField(max_length=255, null=True)),
                ('description', models.TextField(null=True)),
                ('couleur', django.contrib.postgres.fields.jsonb.JSONField(null=True)),
                ('taille', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), size=None)),
                ('en_stock', models.CharField(max_length=255, null=True)),
                ('note', models.CharField(max_length=255, null=True)),
                ('en_promotion', models.CharField(max_length=255, null=True)),
                ('premium', models.CharField(max_length=255, null=True)),
                ('nouveaute', models.CharField(max_length=255, null=True)),
                ('statut', models.BooleanField(default=False, null=True)),
                ('date_add', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_upd', models.DateTimeField(auto_now=True, null=True)),
                ('sous_categorie_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='souscategorieitem', to='myapp.SousCategorieItem')),
            ],
            options={
                'verbose_name': 'Produit',
                'verbose_name_plural': 'Produits',
            },
        ),
        migrations.CreateModel(
            name='Look',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_auteur', models.CharField(max_length=255, null=True)),
                ('image_auteur', models.FileField(upload_to='imageauteur')),
                ('liens_familly', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), null=True, size=None)),
                ('article', models.ManyToManyField(related_name='articlelook', to='myapp.Produit')),
                ('familly', models.ManyToManyField(related_name='famillylook', to='myapp.Look')),
            ],
            options={
                'verbose_name': 'Look',
                'verbose_name_plural': 'Looks',
            },
        ),
        migrations.CreateModel(
            name='ImageProduit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(null=True, upload_to='imageproduit')),
                ('statut', models.BooleanField(default=False, null=True)),
                ('date_add', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_upd', models.DateTimeField(auto_now=True, null=True)),
                ('produit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='produitimage', to='myapp.Produit')),
            ],
            options={
                'verbose_name': 'ImageProduit',
                'verbose_name_plural': 'ImageProduits',
            },
        ),
        migrations.CreateModel(
            name='ImageLook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(null=True, upload_to='imagelook')),
                ('statut', models.BooleanField(default=False, null=True)),
                ('date_add', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_upd', models.DateTimeField(auto_now=True, null=True)),
                ('look', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lookimage', to='myapp.Look')),
            ],
            options={
                'verbose_name': 'ImageLook',
                'verbose_name_plural': 'ImageLooks',
            },
        ),
        migrations.CreateModel(
            name='ImageCollection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(null=True, upload_to='imagecollection')),
                ('statut', models.BooleanField(default=False, null=True)),
                ('date_add', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_upd', models.DateTimeField(auto_now=True, null=True)),
                ('collection', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='collectionimage', to='myapp.Collection')),
            ],
            options={
                'verbose_name': 'ImageCollection',
                'verbose_name_plural': 'ImageCollections',
            },
        ),
        migrations.AddField(
            model_name='collection',
            name='article',
            field=models.ManyToManyField(related_name='articlecollection', to='myapp.Produit'),
        ),
    ]
