# Generated by Django 3.0.7 on 2020-07-06 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categorie',
            name='image',
        ),
        migrations.RemoveField(
            model_name='categorie',
            name='image_nom',
        ),
        migrations.RemoveField(
            model_name='categorie',
            name='image_url',
        ),
        migrations.RemoveField(
            model_name='categorie',
            name='url_key',
        ),
    ]
