# Generated by Django 3.0.7 on 2020-07-06 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20200706_1424'),
    ]

    operations = [
        migrations.AddField(
            model_name='look',
            name='date_add',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='look',
            name='date_upd',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='look',
            name='statut',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
