# Generated by Django 3.0.7 on 2020-07-07 14:23

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20200706_1432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produit',
            name='description',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='souscategorie',
            name='lien',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
