# Generated by Django 3.0.7 on 2020-07-07 15:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_auto_20200707_1423'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategorieLook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255, null=True)),
                ('lien', models.URLField(max_length=255, null=True)),
                ('statut', models.BooleanField(default=False, null=True)),
                ('date_add', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_upd', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name': 'CategorieLook',
                'verbose_name_plural': 'CategorieLooks',
            },
        ),
        migrations.AddField(
            model_name='look',
            name='look',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lookcategorie', to='myapp.CategorieLook'),
        ),
    ]
