# Generated by Django 3.0.7 on 2020-07-10 11:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_auto_20200707_1541'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField(max_length=255, null=True)),
                ('statut', models.BooleanField(default=False, null=True)),
                ('date_add', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_upd', models.DateTimeField(auto_now=True, null=True)),
                ('categorie', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='articlelink', to='myapp.SousCategorie')),
            ],
            options={
                'verbose_name': 'ArticleLink',
                'verbose_name_plural': 'ArticleLinks',
            },
        ),
    ]
