# Generated by Django 3.0.7 on 2020-07-10 11:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_articlelink'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlelink',
            name='categorie',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='articlelink', to='myapp.Categorie'),
        ),
    ]
